apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hrtech-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hrtech-backend:rabbitmq-consumer-v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3175
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hrtech-local
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      port: 3175
      targetPort: 3175