export enum NotificationType {
  LEAVE_REQUEST_CREATED = 'leave_request_created',
  LEAVE_REQUEST_APPROVED = 'leave_request_approved',
  LEAVE_REQUEST_REJECTED = 'leave_request_rejected',
  LEAVE_REQUEST_CANCELLED = 'leave_request_cancelled',
  LEAVE_REQUEST_CHANGES_REQUESTED = 'leave_request_changes_requested',
  CANDIDATE_STAGE_CHANGED = 'candidate_stage_changed',
  CANDIDATE_ASSIGNED = 'candidate_assigned',
  EMPLOYEE_TRANSFERRED = 'employee_transferred',
  ONBOARDING_TASK_ASSIGNED = 'onboarding_task_assigned',
  TASK_ASSIGNED = 'task_assigned',
  TASK_COMMENT_ADDED = 'task_comment_added',
  CALENDAR_INVITATION = 'calendar_invitation',
  MENTION = 'mention',
}
